stages:
  - build
  - test
  - deploy

build metager1:
  tags:
  - 144.76.113.134
  only:
    - master@open-source/MetaGer
  before_script:
    # Abhängigkeiten überprüfen
    - which composer
    - which git
    - which php
    - which sqlite3
  script:
    - sh build.sh
   
build metager2:
  tags:
  - metager2
  only:
    - master@open-source/MetaGer
  before_script:
    # Abhängigkeiten überprüfen
    - which composer
    - which git
    - which php
    - which sqlite3
  script:
    - sh build.sh
    
build metager3:
  stage: build
  tags:
  - metager3
  only:
    - development@open-source/MetaGer
  before_script:
    # Abhängigkeiten überprüfen
    - which composer
    - which git
    - which php
    - which sqlite3
  script:
    - sh build.sh

test metager3:
  stage: test
  tags:
    - metager3
  only:
    - development@open-source/MetaGer
  script:
    - cd ~/MetaGer_neu 
    - sh test.sh
  after_script:
    - kill $browserstackPid
    - kill $servePid

deploy metager3:
  stage: deploy
  tags:
    - metager3
  only:
    - development@open-source/MetaGer
  script:
    - cd ~/MetaGer_neu 
    - sh test.sh