update(metager2):
  tags:
  - 144.76.182.236
  only:
    - Preredesign@open-source/MetaGer
  before_script:
    # Abhängigkeiten überprüfen
    - which composer
    - which git
    - which php
    - which sqlite3
  script:
    # Pfad zum neu geklonten Repo
    - path=`pwd`
    - cd ~/
    - if [ -d .MetaGer_alt ]; then rm -rf .MetaGer_alt;fi
    - git clone "$path" .MetaGer_alt
    - cd .MetaGer_alt
    - composer install
    - scp -P 63824 metager@metager3.de:~/.env .
    - scp -P 63824 metager@metager3.de:~/sumas.xml config/
    - scp -P 63824 metager@metager3.de:~/sumasEn.xml config/
    - scp -P 63824 metager@metager3.de:~/blacklistUrl.txt config/
    - scp -P 63824 metager@metager3.de:~/blacklistDomains.txt config/
    - touch storage/logs/laravel.log
    - touch storage/logs/worker.log
    - touch database/metager.sqlite
    - chmod 777 config/sumas.xml config/sumasEn.xml database/metager.sqlite
    - chmod -R 777 storage
    - chmod -R 777 bootstrap/cache
    - npm install
    - php artisan migrate --force
    - npm run prod
    - if [ -f ~/MetaGer_alt/artisan ]; then php ~/MetaGer_alt/artisan down;fi
    - cd ~/
    - while [ -d ~/MetaGer_alt ]; do rm -rf ~/MetaGer_alt;done
    - mv .MetaGer_alt MetaGer_alt
    - sudo pkill --signal SIGHUP supervisord
    - php ~/MetaGer_alt/artisan up