<?php

return [
    'head.1' => 'Über uns',
    'info.1' => 'Die deutsche Suchmaschine MetaGer wird betrieben und stetig weiterentwickelt vom SUMA-EV - Verein für freien Wissenszugang. Wir sind ein gemeinnützig anerkannter Verein, eines unserer Ziele ist die Entwicklung und der Betrieb von Suchmaschinen. Wir erhalten keine öffentlichen Fördergelder und sind daher auf Ihre Spenden angewiesen. Wir haben unsere Werbung stark reduziert, denn wir vertrauen auf IHRE Unterstützung.
Helfen Sie mit, dass freie Suchmaschinen im Internet frei bleiben und stetig weiterentwickelt werden!
Das können Sie mit einer Spende auf dieser Seite tun. Oder, wenn Sie freie Suchmaschinen auch langfristig sichern wollen:
            <a href="https://metager.de/beitritt" target="_blank" rel="noopener">Werden Sie Mitglied im Trägerverein von MetaGer, dem SUMA-EV.</a>',
    'info.2' => 'Für Spenden können Sie unser <a href="/spende" rel="noopener" target="_blank">Spendenformular</a> nutzen. Oder werden Sie Mitglied (<a href="/beitritt" target="_blank" rel="noopener">zum Aufnahmeantrag</a>); Sie haben dann die Möglichkeit, auf den Seiten des SUMA-EV gegebenfalls Ihr Logo mit einem kurzen Text unterzubringen. Wie das aussieht, sehen Sie hier: <a href="https://suma-ev.de/suma-links/index.html#sponsors" target="_blank" rel="noopener">Sponsorenseite</a> und auch auf dieser Seite: <a href="https://suma-ev.de/mitglieder/index.html" target="_blank" rel="noopener">SUMA-EV Mitglieder</a>. Oder <a href="/spende" target="_blank" rel="noopener">werden Sie SUMA-EV Förderer!</a>',
    'info.3' => '<a href="https://suma-ev.de/unterstuetzung/index.html" target="_blank" rel="noopener">JEDE Form Ihrer Unterstützung</a> hilft mit, dass freie Suchmaschinen und freier Wissenszugang im Internet eine Chance haben. Zum freien Wissenszugang gehört es auch, dass Ihre Daten weder überwacht, noch Ihre Internet-Adressen und Verbindungsdaten gespeichert werden. Bei uns wird Ihre Internet-Adresse bereits während der Suche anonymisiert, sie wird nicht gespeichert und nicht an Dritte weitergegeben. Freie Internet-Suche ohne Überwachung: <a href="/" target="_blank" rel="noopener">MetaGer.de!</a>',
    'info.4' => 'Eine weitere Möglichkeit, MetaGer zu fördern, besteht darin, dass Sie Ihren nächsten Online-Einkauf bei MetaGer-Fördershops machen. Damit wir auf diesem Weg unterstützt werden können, haben wir uns in das Netzwerk zur Förderung gemeinnützig anerkannter Organisationen eingebracht, das Projekt <a href="https://www.wecanhelp.de/430159004" target="_blank" rel="noopener">www.wecanhelp.de</a> Unter dem Dach dieses Projektes sind ca. 400 Online-Shops (von 1und1 bis Zooplus) vereint, die sich bereit erklärt haben, von allen Verkäufen etwa 6% an das Projekt zu spenden. Statt wie bisher direkt zum Online-Shop zu surfen, gehen Sie zunächst auf <a href="/" target="_blank" rel="noopener">MetaGer.de!</a> und klicken dort oben in der Navigationsleiste auf "Fördern", dann auf <a href="https://www.wecanhelp.de/430159004" target="_blank" rel="noopener">"Einkaufen bei MetaGer Fördershops"</a>. Dieser Klick führt Sie in die Shop-Auswahl des Boost-Projektes. Dort suchen Sie sich Ihren Shop aus und machen wie gewohnt Ihren Einkauf. Oder klicken Sie für Einkäufe aus dem Bereich Schreibwaren, Büro- und Geschenkartikel beispielsweise direkt auf <a href="https://www.gladizon.com/" target="_blank" rel="noopener">www.gladizon.com</a>. Das ist alles. Wenn genug Menschen dies tun, dann brauchen wir keine Werbung mehr. Nur zwei Mausklicks für Sie - für alle eine Chance für den freien Wissenszugang in der digitalen Welt.',

];